import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-between items-center h-[80px] max-w-[900px] m-auto">
          <nav className="flex justify-between w-[30%]">
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/timer">Timer</Link>
          </nav>
          <button>다크모드</button>
        </header>
        <hr className="mb-[40px]" />
        <main className="max-w-[900px] m-auto">{children}</main>
        <footer className="text-center">
          JunSeok Lee • © 2023 • https://JunSeokBlog.com
        </footer>
      </body>
    </html>
  );
}
